# Configurações do Banco de Dados PostgreSQL (rodando no Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/fisico_quimica
spring.datasource.username=admin
spring.datasource.password=adminpassword

# Configuração do Hibernate (O substituto do Prisma)
# update: cria/atualiza as tabelas automaticamente baseado nas entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configuração da Porta do Servidor Web
server.port=8080
